openapi: 3.0.1
info:
  title: Product API
  description: API for managing and retrieving product data.
  version: 1.0.0
servers:
  - url: https://{api-id}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      api-id:
        default: your-api-id
      region:
        default: us-west-2
      stage:
        default: prod
paths:
  /products:
    get:
      summary: Retrieve all products
      operationId: getProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: ok
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: prod-52
                        name:
                          type: string
                          example: Product 52
                        category:
                          type: string
                          example: Books
                        price:
                          type: number
                          example: 59
                        inStock:
                          type: boolean
                          example: true
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
  /products/{id}:
    get:
      summary: Retrieve a product by ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: prod-52
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: prod-52
                  name:
                    type: string
                    example: Product 52
                  category:
                    type: string
                    example: Books
                  price:
                    type: number
                    example: 59
                  inStock:
                    type: boolean
                    example: true
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
